name: Build Kernel with NetHunter Patch

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/piashlofkw-cyber/android_kernel_nubia_sm8350
          kernel-branch: lineage-20
          config: lahaina-qgki_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 13
          nethunter: true
          anykernel3: true
          release: true
          access-token: ${{ secrets.GH_TOKEN }}
